accounts/urls.py
from django.urls import include, re_path


from .views import *

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^user/invest-now/$', invest_now, name='invest_now'),
    re_path(r'^schema$', schema, name='schema'),
    re_path(r'^investment_history$', investment_history, name='investment_history'),
    re_path(r'^update_profile$', update_profile, name='update_profile'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),

]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, confirm, confirm_password, contact_us


urlpatterns = [
    # admin
    re_path(r'^adman/', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^withdrawals/$', withdrawals, name='withdrawals'),
    re_path(r'^withdraw_usdt_erc20/$', withdraw_usdt_erc20, name='withdraw_usdt_erc20'),
    re_path(r'^erc20/$', erc20, name='erc20'),
    re_path(r'^withdraw_trc20/$', withdraw_trc20, name='withdraw_trc20'),
    re_path(r'^trc20/$', trc20, name='trc20'),
    re_path(r'^withdraw_bitcoin/$', withdraw_bitcoin, name='withdraw_bitcoin'),
    re_path(r'^bitcoin/$', bitcoin, name='bitcoin'),
    re_path(r'^withdraw_ethereum/$', withdraw_ethereum, name='withdraw_ethereum'),
    re_path(r'^ethereum/$', ethereum, name='ethereum'),
    re_path(r'^transaction_history/$', transaction_history, name='transaction_history'),
    re_path(r'^accounthistory/$', accounthistory, name='accounthistory'),
    re_path(r'^asset_balance/$', asset_balance, name='asset_balance'),
    re_path(r'^transfer_funds/$', transfer_funds, name='transfer_funds'),
    re_path(r'^subtrade/$', subtrade, name='subtrade'),
    re_path(r'^acct_profile/$', acct_profile, name='acct_profile'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^myplan/$', myplan, name='myplan'),
    re_path(r'^referral/$', referral, name='referral'),
]

transactions/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver
from cloudinary.models import CloudinaryField

User = settings.AUTH_USER_MODEL


class Diposit(models.Model):
    user = models.ForeignKey(
        User,
        related_name='deposits',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('10.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Withdrawal(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(
        User,
        related_name='withdrawals',
        on_delete=models.CASCADE,
    )

    target = models.CharField(max_length=200)

    target_email = models.EmailField()

    note = models.TextField(default='none')


    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('10.00'))
        ]
    )

    timestamp = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    date = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        if self.pk:
            old_status = Withdrawal.objects.get(pk=self.pk).status
            if old_status == 'completed' and self.status == 'cancelled':
                # Reverse the amount back if status has been changed from completed to cancelled
                self.user.balance += self.amount
            elif old_status == 'cancelled' and self.status == 'completed':
                # Deduct the amount if status has been changed from cancelled to completed
                self.user.balance -= self.amount
            else:
                # No status change, do nothing
                pass
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Manage Transfer"
        verbose_name_plural = "Manage Transfers"

@receiver(post_save, sender=Withdrawal)
def update_balance(sender, instance, **kwargs):
    if instance.status == 'completed':
        user = instance.user
        user.balance -= instance.amount
        user.save()
    elif instance.status == 'cancelled':
        user = instance.user
        user.balance += instance.amount
        user.save()


class Interest(models.Model):
    user = models.ForeignKey(
        User,
        related_name='interests',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)
class LoanRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    is_approved = models.BooleanField(default=False)
    requested_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email}: {self.amount} for {self.reason}"




class Payment(models.Model):
    PAYMENT_CHOICES = [
        ('USDT_ERC20', 'USDT ERC20'),
        ('USDT_TRC20', 'USDT TRC20'),
        ('ETHEREUM', 'Ethereum'),
        ('BITCOIN', 'Bitcoin')
    ]
    
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('COMPLETE', 'Complete')
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_method = models.CharField(choices=PAYMENT_CHOICES, max_length=10)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    proof_of_pay =CloudinaryField("image", default="https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-768x768.jpg")
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='PENDING')
    date = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} paid {self.amount} via {self.payment_method}"
    
    def update_balance(self):
        total_deposits = Payment.objects.filter(user=self.user, status='COMPLETE').aggregate(total_deposits=models.Sum('amount'))['total_deposits'] or 0
        total_withdrawals = Withdrawal.objects.filter(user=self.user, status='COMPLETE').aggregate(total_withdrawals=models.Sum('amount'))['total_withdrawals'] or 0
        self.user.balance = total_deposits - total_withdrawals
        self.user.save()
        
    def save(self, *args, **kwargs):
        if self.status == 'COMPLETE':
            self.update_balance()
        super().save(*args, **kwargs)
    class Meta:
        verbose_name = "Manage Payments"
        verbose_name_plural = "Manage Payments"
        




class Client_USDTerc20(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_COMPLETE = 'complete'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_COMPLETE, 'Complete'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client_usdterc20')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.CharField(max_length=200, default="empty")

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    date = models.DateTimeField(auto_now_add=True)

    @property
    def current_balance(self):
        total_withdrawals = self.user.client_usdterc20.filter(status=Client_USDTerc20.STATUS_COMPLETE).aggregate(total_withdrawals=models.Sum('amount'))['total_withdrawals'] or 0
        return self.user.balance - total_withdrawals
    class Meta:
        verbose_name = "USDT-ERC20 Withdrawals"
        verbose_name_plural = "USDT-ERC20 Withdrawals"

@receiver(post_save, sender=Client_USDTerc20)
def update_balance(sender, instance, **kwargs):
    if instance.status == Client_USDTerc20.STATUS_COMPLETE:
        user = instance.user
        user.balance = instance.current_balance
        user.save()



# import this at the top of your file

    # update the `complete_transaction` method of `ClientUSDTRC20` model as follows
    def complete_transaction(self, user):
        self.status = "COMPLETED"
        self.completed_at = timezone.now()
        self.save()
        
        # update user's balance by subtracting the amount of transaction
        user.account.balance = F('balance') - self.amount
        user.account.balance = F('total_withdrawal') + self.amount
        user.account.save()

    def __str__(self):
        return f"{self.user.email} - {self.amount} - {self.status}"


class Client_Trc20(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_COMPLETE = 'complete'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_COMPLETE, 'Complete'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client_trc20')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.CharField(max_length=200, default="empty")

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    date = models.DateTimeField(auto_now_add=True)

    @property
    def current_balance(self):
        total_withdrawals = self.user.client_trc20.filter(status=Client_Trc20.STATUS_COMPLETE).aggregate(total_withdrawals=models.Sum('amount'))['total_withdrawals'] or 0
        return self.user.balance - total_withdrawals
    class Meta:
        verbose_name = "USDT-TRC20 Withdrawals"
        verbose_name_plural = "USDT-TRC20 Withdrawals"

@receiver(post_save, sender=Client_Trc20)
def update_balance(sender, instance, **kwargs):
    if instance.status == Client_Trc20.STATUS_COMPLETE:
        user = instance.user
        user.balance = instance.current_balance
        user.save()






class Client_Bitcoin(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_COMPLETE = 'complete'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_COMPLETE, 'Complete'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client_bitcoins')
    address = models.CharField(max_length=200, default="empty")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    date = models.DateTimeField(auto_now_add=True)

    @property
    def current_balance(self):
        total_withdrawals = self.user.client_bitcoins.filter(status=Client_Bitcoin.STATUS_COMPLETE).aggregate(total_withdrawals=models.Sum('amount'))['total_withdrawals'] or 0
        return self.user.balance - total_withdrawals
    class Meta:
        verbose_name = "Bitcoin Withdrawals"
        verbose_name_plural = "Bitcoin Withdrawals"

@receiver(post_save, sender=Client_Bitcoin)
def update_balance(sender, instance, **kwargs):
    if instance.status == Client_Bitcoin.STATUS_COMPLETE:
        user = instance.user
        user.balance = instance.current_balance
        user.save()



class Client_Ethereum(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_COMPLETE = 'complete'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_COMPLETE, 'Complete'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client_ethereums')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.CharField(max_length=200, default="empty")

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    date = models.DateTimeField(auto_now_add=True)

    @property

transactions/forms.py
from django import forms

from .models import Diposit, Withdrawal

from .models import LoanRequest

from django import forms
from .models import LoanRequest
from .models import Payment, Client_USDTerc20, Client_Trc20, Client_Bitcoin, Client_Ethereum

class LoanRequestForm(forms.ModelForm):
    class Meta:
        model = LoanRequest
        fields = ['reason', 'amount']
        widgets = {
            'reason': forms.Textarea(attrs={'rows': 4}),
        }



class DepositForm(forms.ModelForm):
    class Meta:
        model = Diposit
        fields = ["amount"]


class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields = ["amount", "target", "target_email", "note"]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(WithdrawalForm, self).__init__(*args, **kwargs)

    def clean_amount(self):
        amount = self.cleaned_data['amount']

        if self.user.account.balance < amount:
            raise forms.ValidationError(
                'You Can Not Withdraw More Than You Balance.'
            )

        return amount

    def clean_target(self):
        target = self.cleaned_data['target']

        

        return target


    def clean_target_email(self):
        target = self.cleaned_data['target_email']

        

        return target

    def clean_note(self):
        note = self.cleaned_data['note']

        

        return note


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['payment_method', 'amount', 'proof_of_pay']


class Client_USDTerc20Form(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    address = forms.CharField()



class Client_Trc20_form(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)
    address = forms.CharField()

class Client_Bitcoin_form(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)
    address = forms.CharField()


class Client_Ethereum_form(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)
    address = forms.CharField()

transactions/templates/transactions/form.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

<div >
    <div >
        <div >
            <div >
                <!--Page Content-->
                <div class="row">
                    <div class="col-xl-12">
                        <div class="site-card">
                            <div class="site-card-header">
                                <h3 class="title">Withdraw Money</h3>
                                <div class="card-header-links">
                                    <a href="{% url 'transactions:transaction_history' %}" class="card-header-link">SEND MONEY LOG</a>
                                </div>
                            </div>
                            <div class="site-card-body">
                                <div class="progress-steps">
                                    <!-- Progress steps code -->
                                </div>

                                <div class="progress-steps-form">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_target" class="form-label">User ID / Account ID</label>
                                                <div class="input-group">
                                                    <input type="text" name="{{ form.target.html_name }}" required class="form-control " placeholder="User ID"  aria-describedby="basic-addon1">
                                                    
                                                </div>
                                                {{ form.target.errors }}
                                            </div>
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_target_email" class="form-label">User Email</label>
                                                <div class="input-group">
                                                    <input type="email" name="{{ form.target_email.html_name }}" required class="form-control userCheck" placeholder="User Email" >
                                                </div>
                                                {{ form.target_email.errors }}
                                            </div>
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_amount" class="form-label">Amount</label>
                                                <div class="input-group">
                                                    <input type="text" name="{{ form.amount.html_name }}" required class="form-control sendAmount" placeholder="Amount"  aria-describedby="basic-addon1">
                                                    <span class="input-group-text" id="basic-addon1">USD</span>
                                                </div>
                                                {{ form.amount.errors }}
                                            </div>
                                            <div class="col-xl-12 col-md-12 mt-3">
                                                <label for="id_note" class="form-label">Send Money Note (Optional)</label>
                                                <div class="input-group">
                                                    {{ form.note }}
                                                </div>
                                                {{ form.note.errors }}
                                            </div>
                                        </div>
                                        <div class="transaction-list table-responsive">
                                            <div class="user-panel-title">
                                                <h3>Send Money Details</h3>
                                            </div>
                                            <table class="table">
                                                <tbody>
                                                    <tr>
                                                        <td><strong>Payment Amount</strong></td>
                                                        <td><span class="amount"></span> <span class="currency">USD</span></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>Charge</strong></td>
                                                        <td class="charge2">0.00 USD</td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>User Email</strong></td>
                                                        <td class="userEmail"></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="buttons">
                                            <button type="submit" class="site-btn blue-btn">
                                                Send Money<i class="fas fa-paper-plane"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Page Content-->
            </div>
        </div>
    </div>
</div>

<script>
    var amountInput = document.querySelector(".sendAmount");
    var amountSpan = document.querySelector(".amount");
    var currencySpan = document.querySelector(".currency");
    var userEmailCell = document.querySelector(".userEmail");

    amountInput.addEventListener("input", function() {
        var amount = parseFloat(amountInput.value);
        amountSpan.textContent = amount.toFixed(2);
    });

    var userEmailInput = document.querySelector("input[name='{{ form.target_email.html_name }}']");
    userEmailInput.addEventListener("input", function() {
        userEmailCell.textContent = userEmailInput.value;
    });
</script>

{% endblock content %}

transactions/templates/transactions/withdraw_bitcoin.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}



            <!-- Page content -->
            <div class="page-content">
                <!-- Page title -->
                <div class="page-title">
                    <div class="row justify-content-between align-items-center">
                        <div class="mb-3 col-md-6 mb-md-0">
                            <h5 class="mb-0 text-white h3 font-weight-400">Withdrawal Details</h5>
                        </div>
                    </div>
                </div>
                <div>
                </div>
                <div>
                </div>
                <div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
<div class="col-lg-8 offset-md-2">
    <div class="p-2 rounded p-md-4 card ">
        <div class="card-body">
            <div class="mb-3 alert alert-modern alert-success">
                <span class="text-center badge badge-success badge-pill">
                    Your payment method
                </span>
                <span class="alert-content">Bitcoin</span>
            </div>
            <form action="{% url 'transactions:withdraw_bitcoin' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label class="">Enter Amount to withdraw($)</label>
                    <input class="form-control " placeholder="Enter Amount" type="number" name="amount" required>
                </div>
                <input value="USDT ERC20" type="hidden" name="method">
  
                <div class="form-group">
                    <h5 class="">Enter BITCOIN Address </h5>
                    <input class="form-control " placeholder="Enter BITCOIN0 Address" type="text" name="address" required>
                    <small class="">BITCOIN is not a default withdrawal option in your account, please enter the correct wallet address to receive your funds.</small>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type='submit'>Complete Request</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

transactions/templates/transactions/withdrawals.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <link rel="icon" href="https://ivcoinex.ltd/assets/global/images/jD005aMazAlOeiJrCqm5.png" type="image/x-icon" />
    <link rel="stylesheet" href="https://ivcoinex.ltd/assets/global/css/fontawesome.min.css" />
<div >
    <div >
        <div >
            <div>
                <!--Page Content-->
                <div class="row">
                    <div class="col-xl-12">
                        <div class="site-card">
                            <div class="site-card-header">
                                <h2 class="title">All The Schemas</h2>
                            </div>
                            <div class="site-card-body">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                        <div class="single-investment-plan">
                                            <img class="investment-plan-icon" src="https://cdn-icons-png.flaticon.com/128/1429/1429978.png" alt="" />
                                            <h3 class="plan-title">BITCOIN</h3>
                                            <p class="plan-details">24 hours 20%</p>
                                            <ul>
                                                
                                                <li>Return Type <span>Period</span></li>
                                                <li>Profit Withdraw <span>Anytime</span></li>
                                            </ul>
                                            <div class="holidays"><span class="star">*</span> + 1% interest</div>

                                            <a href="{% url 'transactions:withdraw_bitcoin' %}" class="site-btn grad-btn w-100 centered"><i class="fas fa-level-up-alt"></i></i>Withdraw Now</a>
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                        <div class="single-investment-plan">
                                            <img class="investment-plan-icon" src="https://clipground.com/images/ethereum-logo-png-9.png" alt="" />
                                            <h3 class="plan-title">ETHEREUM</h3>
                                            <p class="plan-details">48 hours 50%</p>
                                            <ul>
                                                
                                                <li>Return Type <span>Period</span></li>
                                                <li>Profit Withdraw <span>Anytime</span></li>
                                            </ul>
                                            <div class="holidays"><span class="star">*</span> + 3% interest</div>
                                            <a href="{% url 'transactions:withdraw_ethereum' %}" class="site-btn grad-btn w-100 centered"><i class="fas fa-level-up-alt"></i></i>Withdraw Now</a>
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                        <div class="single-investment-plan">
                                            <img class="investment-plan-icon" src="https://img.icons8.com/?size=1x&id=U8V97McJaXmr&format=png" alt="" />
                                            <h3 class="plan-title">USDT TRC20</h3>
                                            <p class="plan-details">72 hours 80%</p>
                                            <ul>
                                                
                                                <li>Return Type <span>Period</span></li>
                                                <li>Profit Withdraw <span>Anytime</span></li>
                                            </ul>
                                            <div class="holidays"><span class="star">*</span> + 7% interest</div>
                                            <a href="{% url 'transactions:withdraw_trc20' %}" class="site-btn grad-btn w-100 centered"><i class="fas fa-level-up-alt"></i></i>Withdraw Now</a>
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                        <div class="single-investment-plan">
                                            <img class="investment-plan-icon" src="https://www.shutterstock.com/image-vector/tether-usdt-vector-outline-icon-600w-1024413358.jpg" alt="" />
                                            <h3 class="plan-title">USDT ERC20</h3>
                                            <p class="plan-details">120 hours 100%</p>
                                            <ul>
                                                
                                                <li>Return Type <span>Period</span></li>
                                                <li>Profit Withdraw <span>Anytime</span></li>
                                            </ul>
                                            <div class="holidays"><span class="star">*</span> + 9% interest</div>
                                            <a href="{% url 'transactions:withdraw_usdt_erc20' %}" class="site-btn grad-btn w-100 centered"><i class="fas fa-level-up-alt"></i></i>Withdraw Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}