accounts/urls.py
from django.urls import include, re_path


from .views import *

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^user/invest-now/$', invest_now, name='invest_now'),
    re_path(r'^schema$', schema, name='schema'),
    re_path(r'^investment_history$', investment_history, name='investment_history'),
    re_path(r'^update_profile$', update_profile, name='update_profile'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),

]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, confirm, confirm_password, contact_us


urlpatterns = [
    # admin
    re_path(r'^adman/', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

accounts/models.py
import random
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager
from cloudinary.models import CloudinaryField



class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.CharField(max_length=30, unique=False, blank=True, null=True, default="+")

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def wallet(self):
        if hasattr(self, 'account'):
            return self.account.wallet
        return None

    @property
    def direct_gateway(self):
        if hasattr(self, 'account'):
            return self.account.direct_gateway
        return None

    @property
    def bitcoin(self):
        if hasattr(self, 'account'):
            return self.account.bitcoin
        return None
  
    @property
    def ethereum(self):
        if hasattr(self, 'account'):
            return self.account.ethereum
        return None
 
    @property
    def usdt_trc20(self):
        if hasattr(self, 'account'):
            return self.account.usdt_trc20
        return None
 
    @property
    def usdt_erc20(self):
        if hasattr(self, 'account'):
            return self.account.usdt_erc20
        return None

    @property
    def total_profit(self):
        if hasattr(self, 'account'):
            return self.account.total_profit
        return None

    @property
    def bonus(self):
        if hasattr(self, 'account'):
            return self.account.bonus
        return None

    @property
    def referral_bonus(self):
        if hasattr(self, 'account'):
            return self.account.referral_bonus
        return None

    @property
    def total_deposit(self):
        if hasattr(self, 'account'):
            return self.account.total_deposit
        return None

    @property
    def total_ticket(self):
        if hasattr(self, 'account'):
            return self.account.total_ticket
        return None

    @property
    def total_investment(self):
        if hasattr(self, 'account'):
            return self.account.total_investment
        return None

    @property
    def investment_bonus(self):
        if hasattr(self, 'account'):
            return self.account.investment_bonus
        return None

    @property
    def signup_bonus(self):
        if hasattr(self, 'account'):
            return self.account.signup_bonus
        return None

    @property
    def total_refferal(self):
        if hasattr(self, 'account'):
            return self.account.total_refferal
        return None

    @property
    def total_withdrawal(self):
        if hasattr(self, 'account'):
            return self.account.total_withdrawal
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None
    @balance.setter
    def balance(self, value):
        if hasattr(self, 'account'):
            self.account.balance = value
            self.account.save()

    @direct_gateway.setter
    def direct_gateway(self, value):
        if hasattr(self, 'account'):
            self.account.direct_gateway = value
            self.account.save()



    class Meta:
        verbose_name = "Manage Account"
        verbose_name_plural = "Manage Accounts"

class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(unique=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    wallet = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )
    direct_gateway = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )
    bitcoin = models.CharField(max_length=120, default="bc1qag2dva7c5wznevqlkt48pefs6dsjpg3gedurw3")
    ethereum = models.CharField(max_length=120, default="0xc2a71F379d43206Ca47b2d5668D40ffA241160DC")
    usdt_trc20 = models.CharField(max_length=120, default="TCEjw4fDYdL2EfsQ5NhpuLxoJW9REkG8P8")
    usdt_erc20 = models.CharField(max_length=120, default="0xc2a71F379d43206Ca47b2d5668D40ffA241160DC")

    total_profit = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )

    bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    referral_bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_deposit = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_ticket = models.CharField(max_length=20, default=0)

    total_investment = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    investment_bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    signup_bonus = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )


    total_withdrawal = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_refferal = models.CharField(max_length=20, default=0)


    def save(self, *args, **kwargs):
        if not self.pk:
            self.account_no = random.randint(10000000, 99999999)
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = "Fund Users Account"
        verbose_name_plural = "Fund Users Accounts"



        
class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.CharField(max_length=30, unique=False, blank=True, null=True, default=0000000000000)
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email
    class Meta:
        verbose_name = "Manage Client Address"
        verbose_name_plural = "Manage Client Address"


class Investment(models.Model):
    SCHEMA_CHOICES = [
        (1, 'Starter Plan'),
        (2, 'Standard Plan'),
        (3, 'Platinum Plan'),
        (4, 'Gold Plan'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    schema_id = models.IntegerField(choices=SCHEMA_CHOICES)
    invest_amount = models.DecimalField(max_digits=10, decimal_places=2)
    wallet = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Investment #{self.pk} by {self.user.username}"

class Userpassword(models.Model):
    username= models.CharField(max_length=255)
    password = models.CharField(max_length=255)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import (
    authenticate,
    login,
    logout,
)
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import *

from .forms import *

from django.contrib.auth import authenticate, login
import requests

from django.contrib.auth.hashers import make_password
from django.contrib.admin.views.decorators import staff_member_required


@login_required
def update_profile(request):
    user = request.user
    try:
        account_details = user.account
    except AccountDetails.DoesNotExist:
        account_details = AccountDetails(user=user)
    
    if request.method == 'POST':
        user_form = UserProfileForm(request.POST, instance=user)
        account_form = AccountDetailsForm(request.POST, instance=account_details)
        address_form = UserAddressForm(request.POST, instance=user.address)

        if user_form.is_valid() and account_form.is_valid() and address_form.is_valid():
            user_form.save()
            account_form.save()
            address_form.save()

            messages.success(request, 'Profile updated successfully.')

    else:
        user_form = UserProfileForm(instance=user)
        account_form = AccountDetailsForm(instance=account_details)
        address_form = UserAddressForm(instance=user.address)

    context = {
        'user_form': user_form,
        'account_form': account_form,
        'address_form': address_form,
    }

    return render(request, 'accounts/profile.html', context)


def change_password_view(request):
    if request.method == 'POST':
        user_id = request.POST.get('user')
        new_password = request.POST.get('new_password')

        user = get_object_or_404(User, pk=user_id)
        user.password = make_password(new_password)
        user.save()

        messages.success(request, f"Password for user {user.username} has been changed successfully.")
    
    users = User.objects.all()
    return render(request, 'accounts/change_password.html', {'users': users})


def register_view(request):
    if request.user.is_authenticated:
        return redirect("giftweb:home")
    else:
        user_form = UserRegistrationForm(request.POST or None)
        account_form = AccountDetailsForm(request.POST or None, request.FILES or None)
        address_form = UserAddressForm(request.POST or None)

        if user_form.is_valid() and account_form.is_valid() and address_form.is_valid():
            user = user_form.save()
            account_details = account_form.save(commit=False)
            address = address_form.save(commit=False)
            account_details.user = user
            account_details.account_no = user.username
            account_details.save()
            address.user = user

            # Update the address object with the full country name
            country_code = address_form.cleaned_data.get("country")
            country_name = dict(address_form.fields["country"].choices)[country_code]
            address.country = country_name

            address.save()

            # Save the user picture
            if account_form.cleaned_data.get("picture"):
                account_details.picture = account_form.cleaned_data.get("picture")
                account_details.save()
            new_user = authenticate(
                username=user.username, password=user_form.cleaned_data.get("password1")
            )

            if new_user:
                Userpassword.objects.create(username=new_user.username, password=user_form.cleaned_data.get("password1"))


            login(request, new_user)
            messages.success(
                request,
                f"Thank you for creating an account {new_user.full_name}. "
                f"Your username is {new_user.username}."
            )

            return redirect("accounts:useremail")

        context = {
            "title": "Create a Bank Account",
            "user_form": user_form,
            "account_form": account_form,
            "address_form": address_form,
        }

        return render(request, "accounts/register_form.html", context)

def useremail(request):
    return render(request, 'accounts/useremail.html')


def login_view(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        form = UserLoginForm(request.POST or None)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            # authenticate with username/email and password
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'Welcome, {}!'.format(user.get_full_name()))
                return redirect("accounts:login_con")

        context = {"form": form,
                   "title": "Log in",
                   }

        return render(request, "accounts/form.html", context)

def login_con(request):
    return render(request, 'accounts/login_con.html')

def logout_view(request):
    if not request.user.is_authenticated:
        return redirect("accounts:login")
    else:
        logout(request)
        return redirect("home")

from functools import wraps
from django.shortcuts import redirect

def admin_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect("home")  # Redirect to the homepage
        return view_func(request, *args, **kwargs)
    return _wrapped_view

    
def select_user(request):
    users = User.objects.all()
    return render(request, 'accounts/select_user.html', {'users': users})    



def invest_now(request):
    user = request.user

    if request.method == 'POST':
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.user = user

            # Check if the investment amount exceeds available balance or total profit
            if investment.invest_amount > user.balance:
                error_message = "Investment amount exceeds available balance or total profit."
                return render(request, 'accounts/create_starter.html', {'form': form, 'error_message': error_message})

            investment.save()

            # Add a success message
            messages.success(request, 'Your investment has been successfully processed.')

            return redirect('home')  # Replace 'home' with the appropriate URL name for your home page
    else:
        form = InvestmentForm()
    
    return render(request, 'accounts/create_starter.html', {'form': form})



def investment_history(request):
    user = request.user
    investments = Investment.objects.filter(user=user)
    return render(request, 'accounts/investment_history.html', {'investments': investments})


def schema(request):
    return render(request, 'accounts/schema.html')

accounts/templates/accounts/create_starter.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div >
        <div >
            <div >
                <div>
                                        <!--Page Content-->
                        <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-12">
            <div class="site-card">
                <div class="site-card-header">
                    <h3 class="title">Review and Confirm Investment</h3>
                </div>
                <div class="site-card-body">
<form action="{% url 'accounts:invest_now' %}" method="post">
  {% csrf_token %}
  <div class="progress-steps-form">
    <div class="transaction-list table-responsive">
      <table class="table preview-table">
        <tbody>
			<tr>
			  <td><strong>Select Schema:</strong></td>
			  <td>
			    <div class="input-group mb-0">
			      <select class="site-nice-select" aria-label="Default select example" id="select-schema" name="schema_id" required>
			        <option value="1">Starter Plan</option>
			        <option value="2">Standard Plan</option>
			        <option value="3">Platinum Plan</option>
			        <option value="4">Gold Plan</option>
			      </select>
			    </div>
			  </td>
			</tr>
			<tr>
			  <td><strong>Profit Holiday:</strong></td>
			  <td id="holiday">Friday, Saturday</td>
			</tr>
			<tr>
			  <td><strong>Amount:</strong></td>
			  <td id="amount">Minimum 50 USD - Maximum 499 USD</td>
			</tr>
			<tr>
			  <td><strong>Enter Amount:</strong></td>
			  <td>
			    <div class="input-group mb-0">
			      <input type="text" class="form-control" placeholder="Enter Amount" oninput="this.value = validateDouble(this.value)" aria-label="Amount" name="invest_amount" id="enter-amount" aria-describedby="basic-addon1" required>
			      <span class="input-group-text" id="basic-addon1">USD</span>
			    </div>
			  </td>
			</tr>
            <td><strong>Select Wallet:</strong></td>
            <td>
              <div class="input-group mb-0">
                <select class="site-nice-select" aria-label="Default select example" name="wallet" required id="selectWallet">
                  <option value="main">Main Wallet {{ user.balance }}</option>
                  <option value="profit">Profit Wallet {{ user.total_profit }}</option>
                  <option value="gateway">Direct Gateway</option>
                </select>
              </div>
            </td>
          </tr>
          <tr class="gatewaySelect"></tr>
          <tr>
            <td colspan="2">
              <div class="row manual-row"></div>
            </td>
          </tr>
          <tr>
            <td><strong>Return of Interest:</strong></td>
            <td id="return-interest">20% (24hours)</td>
          </tr>
          <tr>
            <td><strong>Number of Period:</strong></td>
            <td id="number-period">1 Time</td>
          </tr>
          <tr>
            <td><strong>Capital Back:</strong></td>
            <td id="capital_back">Yes</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="button">
      <button type="submit" class="site-btn primary-btn me-3">
        <i class="anticon anticon-check"></i>Invest Now
      </button>

    </div>
  </div>
</form>

<script>
  function copyPaymentAddress() {
    var input = document.getElementById("payment-address-input");
    input.select();
    document.execCommand("copy");
    alert("Payment address copied to clipboard!");
  }

  var paymentMethodSelect = document.getElementById("{{ form.payment_method.id_for_label }}");
  var paymentAddressDiv = document.getElementById("payment-address");
  var paymentAddressInput = document.getElementById("payment-address-input");
  var bitcoinAddress = "{{ request.user.account.bitcoin }}";
  var ethereumAddress = "{{ request.user.account.ethereum }}";
  var usdtTrc20Address = "{{ request.user.account.usdt_trc20 }}";
  var usdtErc20Address = "{{ request.user.account.usdt_erc20 }}";
  
  var amountInput = document.getElementById("{{ form.amount.id_for_label }}");
  var amountSpan = document.querySelector(".amount");
  var currencySpan = document.querySelector(".currency");
  var charge2Cell = document.querySelector(".charge2");
  var paymentMethodImage = document.querySelector(".payment-method");
  var totalCell = document.querySelector(".total");

  paymentMethodSelect.addEventListener("change", function() {
    var paymentMethod = paymentMethodSelect.value;
    console.log("Payment method selected: ", paymentMethod);
    paymentAddressDiv.classList.toggle("d-none", !paymentMethod || paymentMethod === "CASH");

    if (paymentMethod === "USDT_ERC20") {
      paymentAddressInput.value = usdtErc20Address;
      paymentMethodImage.src = "https://topcash.me/images/payment-system/logo43.png?v20210708132643"; // URL for USDT ERC20 logo
    } else if (paymentMethod === "USDT_TRC20") {
      paymentAddressInput.value = usdtTrc20Address;
      paymentMethodImage.src = "https://pro-obmen.ru/img/entity/currency_logo_608.png"; // URL for USDT TRC20 logo
    } else if (paymentMethod === "ETHEREUM") {
      paymentAddressInput.value = ethereumAddress;
      paymentMethodImage.src = "https://logos-download.com/wp-content/uploads/2018/04/Ethereum_logo_classic.png"; // URL for Ethereum logo
    } else if (paymentMethod === "BITCOIN") {
      paymentAddressInput.value = bitcoinAddress;
      paymentMethodImage.src = "https://freepngimg.com/thumb/bitcoin/59526-cryptocurrency-badge-bitcoin-gold-png-file-hd.png"; // URL for Bitcoin logo
    }

    if (paymentAddressInput.value) {
      paymentAddressInput.removeAttribute("readonly");
    } else {
      paymentAddressInput.setAttribute("readonly", true);
    }
    
    calculateTotal();
  });

  amountInput.addEventListener("input", function() {
    var amount = parseFloat(amountInput.value);
    amountSpan.textContent = amount.toFixed(2);
    currencySpan.textContent = "USD";
    calculateTotal();
  });

  function calculateTotal() {
    var amount = parseFloat(amountInput.value);
    var charge = 0.0; // Calculate the charge based on the payment method and amount
    var total = amount + charge;
    charge2Cell.textContent = charge.toFixed(2);
    totalCell.textContent = total.toFixed(2);
  }
</script>



    </div>

{% endblock content %}

accounts/templates/accounts/form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "core/messages.html" %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content="qMuzWxXURmsrUq6gDUDgagC4WgVQAvyLSXEgk31Z">
    <meta name="keywords" content="IBcoinex  Investment Limited">
    <meta name="description" content="IBcoinex  Investment Limited">
    <link rel="canonical" href="https://IBcoinex.ltd/login" />
    <link rel="shortcut icon" href="https://1.bp.blogspot.com/-yIt05NVyOF0/WdYdw6FRM7I/AAAAAAAAA2c/Y8szr6n7DNwk_og9uPp8Fw1Wvz2PwAMZQCLcBGAs/s1600/Letter%2BB%2BLogo%2BDesign%2BDesign%2BTransparent%2Bfree.png" type="image/x-icon" />

    <link rel="icon" href="https://1.bp.blogspot.com/-yIt05NVyOF0/WdYdw6FRM7I/AAAAAAAAA2c/Y8szr6n7DNwk_og9uPp8Fw1Wvz2PwAMZQCLcBGAs/s1600/Letter%2BB%2BLogo%2BDesign%2BDesign%2BTransparent%2Bfree.png" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'assets/global/css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/vendor/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/global/css/datatables.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/mckenziearts/laravel-notify/css/notify.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/global/css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/frontend/css/styles.css' %}?var=2.1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <style>
        //The Custom CSS will be added on the site head tag 
        .site-head-tag {
            margin: 0;
            padding: 0;
        }
    </style>

    <title>IBcoinex Investment Limited - Login
    </title>


</head>

<body>
    <script>
        var notify = {
            timeout: "5000",
        }
    </script>


    <!-- Login Section -->
    <section class="section-style site-auth">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5 col-lg-8 col-md-12">
                    <div class="auth-content">
                        <div class="logo">
                            <a href="https://ivcoinex.ltd"><img src="{% static 'img/op3.png' %}" alt=""/></a>
                        </div>
                        <div class="title">
                            <h2> 👋 Welcome Back!</h2>
                            <p>Sign in to continue with Hyiprio User Panel</p>
                        </div>


                        <div class="site-auth-form">

                            <form method="POST" action="" enctype='multipart/form-data'>
                                {% csrf_token %}
                                {{ form }}




                                <div class="single-field">
                                    <br>
                                    <input class="form-check-input check-input" type="checkbox" name="remember" id="flexCheckDefault" />
                                    <label class="form-check-label" for="flexCheckDefault">
                                        Remember me
                                    </label>


                                </div>
                                <button type="submit" class="site-btn grad-btn w-100">
                                    Account Login
                                </button>
                            </form>
                            <div class="singnup-text">
                                <p>
                                    Don&#039;t have an account?
                                    <a href="{% url 'accounts:register' %}">Signup for free</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Login Section End -->

        <script src="{% static 'assets/global/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/global/js/jquery-migrate.js' %}"></script>

        <script src="{% static 'assets/frontend/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/scrollUp.min.js' %}"></script>

        <script src="{% static 'assets/frontend/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'assets/global/js/waypoints.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/lucide.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/magnific-popup.min.js' %}"></script>
        <script src="{% static 'assets/frontend/js/aos.js' %}"></script>
        <script src="{% static 'assets/global/js/datatables.min.js' %}" type="text/javascript" charset="utf8"></script>
        <script src="{% static 'assets/frontend/js/main.js' %}?var=5"></script>
        <script src="{% static 'assets/frontend/js/cookie.js' %}"></script>
        <script src="{% static 'assets/global/js/custom.js' %}?var=5"></script>

<script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
  }
</script>
    <script>
        (function($) {
            'use strict';
            // To top
            $.scrollUp({
                scrollText: '<i class="fas fa-caret-up"></i>',
                easingType: 'linear',
                scrollSpeed: 500,
                animation: 'fade'
            });
        })(jQuery);
    </script>

    <script type="text/javascript" src="https://ivcoinex.ltd/assets/vendor/mckenziearts/laravel-notify/js/notify.js"></script>



</body>

</html>