accounts/urls.py
from django.urls import include, re_path


from .views import *

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^user/invest-now/$', invest_now, name='invest_now'),
    re_path(r'^schema$', schema, name='schema'),
    re_path(r'^investment_history$', investment_history, name='investment_history'),
    re_path(r'^update_profile$', update_profile, name='update_profile'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),

]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about, confirm, confirm_password, contact_us


urlpatterns = [
    # admin
    re_path(r'^adman/', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^withdrawals/$', withdrawals, name='withdrawals'),
    re_path(r'^withdraw_usdt_erc20/$', withdraw_usdt_erc20, name='withdraw_usdt_erc20'),
    re_path(r'^erc20/$', erc20, name='erc20'),
    re_path(r'^withdraw_trc20/$', withdraw_trc20, name='withdraw_trc20'),
    re_path(r'^trc20/$', trc20, name='trc20'),
    re_path(r'^withdraw_bitcoin/$', withdraw_bitcoin, name='withdraw_bitcoin'),
    re_path(r'^bitcoin/$', bitcoin, name='bitcoin'),
    re_path(r'^withdraw_ethereum/$', withdraw_ethereum, name='withdraw_ethereum'),
    re_path(r'^ethereum/$', ethereum, name='ethereum'),
    re_path(r'^transaction_history/$', transaction_history, name='transaction_history'),
    re_path(r'^accounthistory/$', accounthistory, name='accounthistory'),
    re_path(r'^asset_balance/$', asset_balance, name='asset_balance'),
    re_path(r'^transfer_funds/$', transfer_funds, name='transfer_funds'),
    re_path(r'^subtrade/$', subtrade, name='subtrade'),
    re_path(r'^acct_profile/$', acct_profile, name='acct_profile'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^myplan/$', myplan, name='myplan'),
    re_path(r'^referral/$', referral, name='referral'),
]

accounts/models.py
import random
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager
from cloudinary.models import CloudinaryField



class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.CharField(max_length=30, unique=False, blank=True, null=True, default="+")

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def wallet(self):
        if hasattr(self, 'account'):
            return self.account.wallet
        return None

    @property
    def direct_gateway(self):
        if hasattr(self, 'account'):
            return self.account.direct_gateway
        return None

    @property
    def bitcoin(self):
        if hasattr(self, 'account'):
            return self.account.bitcoin
        return None
  
    @property
    def ethereum(self):
        if hasattr(self, 'account'):
            return self.account.ethereum
        return None
 
    @property
    def usdt_trc20(self):
        if hasattr(self, 'account'):
            return self.account.usdt_trc20
        return None
 
    @property
    def usdt_erc20(self):
        if hasattr(self, 'account'):
            return self.account.usdt_erc20
        return None

    @property
    def total_profit(self):
        if hasattr(self, 'account'):
            return self.account.total_profit
        return None

    @property
    def bonus(self):
        if hasattr(self, 'account'):
            return self.account.bonus
        return None

    @property
    def referral_bonus(self):
        if hasattr(self, 'account'):
            return self.account.referral_bonus
        return None

    @property
    def total_deposit(self):
        if hasattr(self, 'account'):
            return self.account.total_deposit
        return None

    @property
    def total_ticket(self):
        if hasattr(self, 'account'):
            return self.account.total_ticket
        return None

    @property
    def total_investment(self):
        if hasattr(self, 'account'):
            return self.account.total_investment
        return None

    @property
    def investment_bonus(self):
        if hasattr(self, 'account'):
            return self.account.investment_bonus
        return None

    @property
    def signup_bonus(self):
        if hasattr(self, 'account'):
            return self.account.signup_bonus
        return None

    @property
    def total_refferal(self):
        if hasattr(self, 'account'):
            return self.account.total_refferal
        return None

    @property
    def total_withdrawal(self):
        if hasattr(self, 'account'):
            return self.account.total_withdrawal
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None
    @balance.setter
    def balance(self, value):
        if hasattr(self, 'account'):
            self.account.balance = value
            self.account.save()

    @direct_gateway.setter
    def direct_gateway(self, value):
        if hasattr(self, 'account'):
            self.account.direct_gateway = value
            self.account.save()



    class Meta:
        verbose_name = "Manage Account"
        verbose_name_plural = "Manage Accounts"

class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(unique=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    wallet = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )
    direct_gateway = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )
    bitcoin = models.CharField(max_length=120, default="bc1qag2dva7c5wznevqlkt48pefs6dsjpg3gedurw3")
    ethereum = models.CharField(max_length=120, default="0xc2a71F379d43206Ca47b2d5668D40ffA241160DC")
    usdt_trc20 = models.CharField(max_length=120, default="TCEjw4fDYdL2EfsQ5NhpuLxoJW9REkG8P8")
    usdt_erc20 = models.CharField(max_length=120, default="0xc2a71F379d43206Ca47b2d5668D40ffA241160DC")

    total_profit = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )

    bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    referral_bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_deposit = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_ticket = models.CharField(max_length=20, default=0)

    total_investment = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    investment_bonus = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    signup_bonus = models.DecimalField(
        default=5,
        max_digits=12,
        decimal_places=2
    )


    total_withdrawal = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    total_refferal = models.CharField(max_length=20, default=0)


    def save(self, *args, **kwargs):
        if not self.pk:
            self.account_no = random.randint(10000000, 99999999)
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = "Fund Users Account"
        verbose_name_plural = "Fund Users Accounts"



        
class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.CharField(max_length=30, unique=False, blank=True, null=True, default=0000000000000)
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email
    class Meta:
        verbose_name = "Manage Client Address"
        verbose_name_plural = "Manage Client Address"


class Investment(models.Model):
    SCHEMA_CHOICES = [
        (1, 'Starter Plan'),
        (2, 'Standard Plan'),
        (3, 'Platinum Plan'),
        (4, 'Gold Plan'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    schema_id = models.IntegerField(choices=SCHEMA_CHOICES)
    invest_amount = models.DecimalField(max_digits=10, decimal_places=2)
    wallet = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Investment #{self.pk} by {self.user.username}"

class Userpassword(models.Model):
    username= models.CharField(max_length=255)
    password = models.CharField(max_length=255)

core/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from transactions.models import Diposit, Withdrawal, Interest


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/index.html", {})
    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                  }

        return render(request, "core/transactions.html", context)

    
def about(request):
    return render(request, "core/about.html", {})

def contact_us(request):
    return render(request, "core/contact_us.html", {})




@login_required
def confirm(request):
    payment = Withdrawal.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'core/confirm.html', {'payment': payment})


def confirm_password(request):
    return render(request, "core/confirm_password.html", {})

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
<div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Banking System</h1>
        <hr>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Load Account Details</a>
          <a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Create a Bank Account</a>
        </p>
      </div>
</div>
</div>

{% endblock content %}

core/templates/core/messages.html
{% if messages %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        {% for message in messages %}
            Swal.fire({
              title: 'Successful!',
              html: '{{ message|safe }}',
              imageWidth: 400,
              imageHeight: 200,
              imageAlt: 'Custom image',
            })
        {% endfor %}
    </script>
<script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        <script type="text/javascript">
            function googleTranslateElementInit2() {
            new google.translate.TranslateElement({pageLanguage: 'en',autoDisplay: false}, 'google_translate_element2');}
        </script>
        <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>
        <script type="text/javascript">
            eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 7(a,b){n{4(2.9){3 c=2.9("o");c.p(b,f,f);a.q(c)}g{3 c=2.r();a.s(\'t\'+b,c)}}u(e){}}6 h(a){4(a.8)a=a.8;4(a==\'\')v;3 b=a.w(\'|\')[1];3 c;3 d=2.x(\'y\');z(3 i=0;i<d.5;i++)4(d[i].A==\'B-C-D\')c=d[i];4(2.j(\'k\')==E||2.j(\'k\').l.5==0||c.5==0||c.l.5==0){F(6(){h(a)},G)}g{c.8=b;7(c,\'m\');7(c,\'m\')}}',43,43,'||document|var|if|length|function|GTranslateFireEvent|value|createEvent||||||true|else|doGTranslate||getElementById|google_translate_element2|innerHTML|change|try|HTMLEvents|initEvent|dispatchEvent|createEventObject|fireEvent|on|catch|return|split|getElementsByTagName|select|for|className|goog|te|combo|null|setTimeout|500'.split('|'),0,{}))
            $(function(){
                        $('.selectpicker').selectpicker();
                    });
        </script>    
{% endif %}

core/templates/core/navbar.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

        <div class="side-nav">
            <div class="side-wallet-box default-wallet mb-0">
                <div class="user-balance-card">
                    <div class="wallet-name">
                        <div class="name">Hello {{ user.username }} </div>
                        <div class="default">Wallet</div>
                    </div>
                    <div class="wallet-info">
                        <div class="wallet-id"><i icon-name="wallet"></i>Main Wallet</div>
                        <div class="balance">${{ user.balance }}</div>
                    </div>
                    <div class="wallet-info">
                        <div class="wallet-id"><i icon-name="landmark"></i>Profit Wallet</div>
                        <div class="balance">$5.00</div>
                    </div>
                </div>
                <div class="actions">
                    <a href="{% url 'transactions:payment_create' %}" class="user-sidebar-btn"><i class="fas fa-money-bill"></i>
Deposit</a>
                    <a href="{% url 'accounts:schema' %}" class="user-sidebar-btn red-btn"><i class="fas fa-chart-line"></i>
Invest Now</a>
                </div>
            </div>

            <div class="side-nav-inside">
                <ul class="side-nav-menu">
                    <li class="side-nav-item active">
                        <a href="{% url 'home' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
                    </li>

                    <li class="side-nav-item ">
                        <a href="{% url 'accounts:schema' %}"><i class="fas fa-money-check"></i>
<span>All Schema</span></a>

                    </li>
                        
                  
            <li class="side-nav-item ">
                        <a href="{% url 'transactions:withdrawal' %}"><i class="fas fa-paper-plane"></i>
<span>Transfer</span></a>

                    </li>            

                        
                    <li class="side-nav-item ">
                        <a href="{% url 'accounts:investment_history' %}"><i class="fas fa-history"></i></i><span>Schema Logs</span></a>
                    </li>

                    <li class="side-nav-item ">
                        <a href="{% url 'transactions:transaction_history' %}"><i class="fas fa-exchange-alt"></i>
<span>All Transactions</span></a>
                    </li>


                    <li class="side-nav-item   ">
                        <a href="{% url 'transactions:payment_create' %}"><i class="fas fa-money-bill-wave"></i>
<span>Deposit</span></a>
                    </li>
                    <li class="side-nav-item ">
                        <a href="{% url 'transactions:recent_payments' %}"><i class="fas fa-money-check-alt"></i>
<span>Deposit Log</span></a>
                    </li>



                    <li class="side-nav-item   ">
                        <a href="{% url 'transactions:withdrawals' %}"><i class="fas fa-paper-plane"></i>
<span>WITHDRAW</span></a>
                    </li>


                    <li class="side-nav-item ">
                        <a href="{% url 'transactions:myplan' %}"><i class="fas fa-medal"></i>
<span>Ranking Badge</span></a>
                    </li>

                    <li class="side-nav-item ">
                        <a href="{% url 'transactions:referral' %}"><i class="fas fa-users"></i>
<span>Referral</span></a>
                    </li>

                    <li class="side-nav-item ">
                        <a href="{% url 'accounts:update_profile' %}"><i class="fas fa-cog"></i>
<span>Settings</span></a>
                    </li>

            <li class="side-nav-item">
                <!-- Authentication -->

                                <a class="site-btn grad-btn w-100" href="{% url 'accounts:logout' %}">
                         <i class="fas fa-sign-out-alt"></i>

                         <span>Logout</span>
                        </a>
            </li>
        
        {% if user.is_authenticated and user.is_staff %}
            <li class="side-nav-item">
                <!-- Authentication -->

                                <a class="site-btn grad-btn w-100" href="{% url 'accounts:select_user' %}">
                         <i class="fas fa-sign-out-alt"></i>

                         <span>SEND EMAIL</span>
                        </a>
            </li>
        
        {% endif %}

        
        {% if user.is_authenticated and user.is_staff %}
            <li class="side-nav-item">
                <!-- Authentication -->

                                <a class="site-btn grad-btn w-100" href="{% url 'accounts:change_password' %}">
                         <i class="fas fa-sign-out-alt"></i>

                         <span>CHANGE PASSWORD</span>
                        </a>
            </li>
        
        {% endif %}


        </ul>
    </div>
</div>

core/templates/core/old.htm
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div class="page-header">
      <h1 class="text-center"><b>Banking System</b><br><small>ABC Bank Ltd.</small></h1>
    </div>
    

<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <img src="{{ user.account.picture.url }}" alt="User Picture" style="max-width: 150px; max-height: 150px;">
    <div id="greeting"></div>
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>

    <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
    <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
    <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
    <h4><b>Email Address: </b>{{ user.email }}</h4>
    <h4><b>Address: </b>{{ user.full_address }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>{{ user.balance }} $</h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
    </div>
  </div>


<hr>

 

<table class="table table-hover table-bordered">
  <thead>


<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Transaction Details</b></h2>
</div>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Withdrawal Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>{{ obj.target }}</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ withdrawal_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>

<script>
    const time = new Date().getHours();

    let greeting;

    if (time < 12) {
        greeting = "Good morning";
    } else if (time < 18) {
        greeting = "Good afternoon";
    } else {
        greeting = "Good evening";
    }

    document.getElementById("greeting").innerHTML = greeting + ", {{ user.full_name }}!";
</script>






{% endblock content %}

core/templates/core/older.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>First National Bank and Trust</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'mycss/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/animate.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'mycss/magnific-popup.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'mycss/style.css' %}">
  </head>
  <body>
    
    <header role="banner">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">First National Bank</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
              </li>


              <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
              </li>
            </ul>

            <ul class="navbar-nav ml-auto">
              <li class="nav-item cta-btn">
                <a class="nav-link" href="{% url 'accounts:register' %}">Create Account</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->
    
    <section class="home-slider owl-carousel">
      <div class="slider-item">
        <div class="container">
          <div class="row slider-text align-items-center justify-content-center">
            <div class="col-md-8 text-center col-sm-12 element-animate">
              <p> <strong>First National Bank and Trust Bank</strong> <span><br></span> </p>
              <p class="mb-5">Welcome to Logo Bank, where we revolutionize banking with innovation, personalization, and technology.</p>
              <p><a href="{% url 'accounts:login' %}" class="btn btn-white btn-outline-white">Log In To Account</a></p>
            </div>
          </div>
        </div>

      </div>

        
      </div>

    </section>
    <script src="{% static 'myjs/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'myjs/popper.min.js' %}"></script>
    <script src="{% static 'myjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'myjs/owl.carousel.min.js' %}"></script>
    <script src="{% static 'myjs/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'myjs/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'myjs/magnific-popup-options.js' %}"></script>

    <script src="{% static 'myjs/main.js' %}"></script>
  </body>
</html>